apiVersion: graphql.gloo.solo.io/v1beta1
kind: GraphQLApi
metadata:
  name: mock-graphql
  namespace: gloo-system
spec:
  executableSchema:
    executor:
      local:
        enableIntrospection: true
        resolutions:
          Query|productsForHome:
            mockResolver:
              syncResponse:
              -
                id: 1
                author: Bill
                title: My Life
                descriptionHtml: a book description
                pages: 100
                year: 1998
                reviews:
                -
                  reviewer: Sam
                  text: "The best!"
              -
                id: 2
                author: George
                title: Bill's Life
                descriptionHtml: the real story of Bill's life
                pages: 200
                year: 1999
                reviews:
                -
                  reviewer: Bill
                  text: "Meh ... read my book instead"
    schemaDefinition: |
      type Query {
        """Description of a book in HTML"""
        productsForHome: [Product] @resolve(name: "Query|productsForHome")
      }

      """Each book has a product entry"""
      type Product {
        """Unique identifier for books"""
      id: String
      """The book title"""
      title: String
      """Description of a book in HTML"""
      descriptionHtml: String
      """Author of the book"""
      author: String 
      """Total number of pages in the book"""
      pages: Int 
      """Year of original publication"""
      year: Int 
      """List of reader reviews for this book"""
      reviews: [Review] 
      """List of reader ratings for this book"""
      ratings: [Rating] 
      }

      """A book review"""
      type Review {
          """Name of the reviewer"""
          reviewer: String
          """Review details"""
          text: String
      }

      """A book rating"""
      type Rating {
          """Name of the user peforming the rating"""
          reviewer: String
          """Number of stars for this rating"""
          numStars: Int
      }
