apiVersion: graphql.gloo.solo.io/v1beta1
kind: GraphQLApi
metadata:
  name: stitched-gql
  namespace: gloo-system
spec:
  stitchedSchema:
    subschemas:
    - name: default-users-8080
      namespace: gloo-system
      typeMerge:
        User:
          selectionSet: '{ username }'
          queryName: GetUser
          args:
            UserSearch.username: username
    - name: default-reviews-8080
      namespace: gloo-system
    - name: default-products-8080
      namespace: gloo-system
