
type Query {
    productsForHome: [Product]
}

type Product {
    id: String
    title: String
    descriptionHtml: String
    author: String
    pages: Int
    year: Int
    review: [Review]
    ratings: [Rating]
}

type Review {
    reviewer: String
    text: String
}

type Rating {
    reviewer: String
    numStars: Int
}