openapi: 3.0.1
info:
  title: Rating API
  description: This is the Rating API from the Istio BookInfo sample application.
  termsOfService: https://istio.io/
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Learn more about the Istio BookInfo application
  url: https://istio.io/docs/samples/bookinfo.html
servers:
- url: /
tags:
- name: rating
  description: Rating information for a product
paths:
  /ratings{id}:
    get:
      tags:
      - rating
      summary: Get ratings for a product
      description: Get ratings for a product, including stars and their color.
      operationId: getProductRatings
      parameters:
      - name: id
        in: path
        description: Product id
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductRatings'
        400:
          description: Invalid product id
          content: {}
components:
  schemas:
    ProductRatings:
      required:
      - id
      - ratings
      type: object
      properties:
        id:
          type: integer
          description: Product id
          format: int32
        ratings:
          type: object
          additionalProperties:
            type: string
          description: A hashmap where keys are reviewer names, values are number
            of stars
      description: Object containing ratings of a product
