apiVersion: security.policy.gloo.solo.io/v2
kind: CORSPolicy
metadata:
  name: cors-policy
  namespace: gloo-mesh-gateways
spec:
  applyToRoutes:
  - route:
      labels:
        istio: ingressgateway
  config:
    allowMethods:
    - GET
    - POST
    allowHeaders:
    - content-type
    allowOrigins:
    - exact: http://localhost:8090

