apiVersion: apimanagement.gloo.solo.io/v2
kind: GraphQLSchema
metadata:
  name: bookinfo-graphql
  namespace: bookinfo
spec:
  resolved:
    options: 
      enableIntrospection: true
    resolverMapRefs:
    - clusterName: cluster-1
      name: bookinfo-resolvers
      namespace: bookinfo
  schemaRef:
    clusterName: cluster-1
    name: bookinfo-schema
    namespace: bookinfo
