apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: bookinfo-rt
  namespace: bookinfo
spec:
  hosts:
  - '*'
  http:
  - graphql:
      options:
        logSensitiveInfo: true
      schema:
        clusterName: mgmt-cluster
        name: bookinfo-graphql
        namespace: bookinfo
    name: api
    matchers:
    - uri:
        prefix: /graphql
  virtualGateways:
  - name: north-south-gw