apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: graphql
  namespace: bookinfo
  labels:
    istio: ingressgateway
spec:
  hosts:
  - api.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  http:
  - graphql:
      schema:
        name: bookinfo-graphql-schema
        namespace: bookinfo
        clusterName: gg-demo-single
    matchers:
    - uri:
        prefix: /graphql